### ISSUE TITLE
Agent returns an error while spark HS installing

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [rework-space-com/ambari#13]
## Description
Ambari-agent returns an error while Spark History Server deploying. This error related to output decoding. Traceback:
```
stderr: 
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/BGTP/1.0/services/SPARK/package/scripts/spark_client.py", line 55, in <module>
    SparkClient().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 352, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/BGTP/1.0/services/SPARK/package/scripts/spark_client.py", line 34, in install
    self.install_packages(env)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 853, in install_packages
    retry_count=agent_stack_retry_count)
  File "/usr/lib/ambari-agent/lib/resource_management/core/base.py", line 166, in __init__
    self.env.run()
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/ambari-agent/lib/resource_management/core/providers/packaging.py", line 30, in action_install
    self._pkg_manager.install_package(package_name, self.__create_context())
  File "/usr/lib/ambari-agent/lib/ambari_commons/repo_manager/apt_manager.py", line 35, in wrapper
    return function_to_decorate(self, name, *args[2:], **kwargs)
  File "/usr/lib/ambari-agent/lib/ambari_commons/repo_manager/apt_manager.py", line 282, in install_package
    shell.repository_manager_executor(cmd, self.properties, context, env=self.properties.install_cmd_env)
  File "/usr/lib/ambari-agent/lib/ambari_commons/shell.py", line 744, in repository_manager_executor
    should_stop_retries = __handle_retries(cmd, repo_properties, context, call_result, is_first_time, is_last_time)
  File "/usr/lib/ambari-agent/lib/ambari_commons/shell.py", line 689, in __handle_retries
    __update_repo_metadata_after_bad_try(cmd, context, repo_properties, call_result.code, call_result.out)
  File "/usr/lib/ambari-agent/lib/ambari_commons/shell.py", line 715, in __update_repo_metadata_after_bad_try
    _logger.info("Execution of '%s' failed and returned %d. %s" % (string_cmd_from_args_list(cmd), code, out))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1875: ordinal not in range(128)
```

## References
- [Related to this problem Cloudera issue](https://community.cloudera.com/t5/Support-Questions/Install-UnicodeDecodeError-ascii-codec-can-t-decode-byte/m-p/139342)

## Tasks
- [x] Fix ambari-agent bug
- [ ] Upgrade version into 2.7.8.2.0

**Comment by Nazarii-Melnyk** [comment]
Python's default encoding is ASCII which throws UnicodeDecodeError when trying to decode a stream/array of bytes to Unicode. Setting the default encoding to UTF-8 will fix the conversion from bytes to UTF-8 encoded string.

It can be done by adding next code in .py file:
```
reload(sys)
sys.setdefaultencoding('utf-8')
```

\***WARNING**\* This method was removed in Python 3

**Comment by Nazarii-Melnyk** [comment]
To fix this bug was used first method. Issue closed without any merge requests.
