### ISSUE TITLE
Fix Ambari LogSearch startup

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [rework-space-com/ambari#22]
logfeader components after installing fails to start. Logs output:
```
2024-09-06 08:30:15,016 [main] INFO  org.springframework.boot.StartupInfoLogger (StartupInfoLogger.java:50) - Starting LogFeeder on isv-s-hdp-mng-01.example.com with PID 273278 (/usr/lib/ambari-logsearch-logfeeder/libs/ambari-logsearch-logfeeder-2.7.8.4.0.jar started by root in /var/lib/ambari-agent)
2024-09-06 08:30:15,028 [main] INFO  org.springframework.boot.SpringApplication (SpringApplication.java:675) - No active profile set, falling back to default profiles: default
2024-09-06 08:30:15,485 [main] ERROR org.springframework.boot.SpringApplication (SpringApplication.java:858) - Application run failed
java.lang.IllegalArgumentException: String 'null' cannot be converted to LogFeederMode enum
        at org.apache.ambari.logfeeder.conf.LogFeederMode.fromString(LogFeederMode.java:48) ~[ambari-logsearch-logfeeder-2.7.8.4.0.jar:?]
        at org.apache.ambari.logfeeder.conf.condition.NonCloudStorageCondition.matches(NonCloudStorageCondition.java:34) ~[ambari-logsearch-logfeeder-2.7.8.4.0.jar:?]
        at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:181) ~[spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:141) ~[spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:117) ~[spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:327) ~[spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232) ~[spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275) ~[spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95) ~[spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705) ~[spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531) ~[spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
        at org.apache.ambari.logfeeder.LogFeeder.main(LogFeeder.java:40) [ambari-logsearch-logfeeder-2.7.8.4.0.jar:?]
```

**Comment by Nazarii-Melnyk** [comment]
Logsearch Portal consistently returns the following log feed:
```
2024-09-06 08:49:55,888 [setup_collection_hadoop_logs] INFO  org.apache.ambari.logsearch.dao.SolrDaoBase (SolrDaoBase.java:79) - Log Search config not available yet, waiting...
2024-09-06 08:49:56,891 [setup_collection_audit_logs] INFO  org.apache.ambari.logsearch.dao.SolrDaoBase (SolrDaoBase.java:79) - Log Search config not available yet, waiting...
2024-09-06 08:49:56,891 [setup_collection_logsearch_metadata] INFO  org.apache.ambari.logsearch.dao.SolrDaoBase (SolrDaoBase.java:79) - Log Search config not available yet, waiting...
```

Because of this, the LogSearch UI cannot be loaded:

![image](https://github.com/user-attachments/assets/90f27f85-6313-44c5-a278-30458eae27e6)

**Comment by Nazarii-Melnyk** [comment]
There are required to define propery `logfeeder.cloud.storage.mode` and set value `default` for it, because logfeeders startup crashes without it.

**Comment by Nazarii-Melnyk** [comment]
Logfeeder can't start. Logs:
```
024-09-12 17:17:52,884 [main] INFO  org.springframework.boot.StartupInfoLogger (StartupInfoLogger.java:55) - Starting LogFeeder using Java 1.8.0_422 on isv-s-hdp-mng-01.example.com with PID 2724410 (/usr/lib/ambari-logsearch-logfeeder/libs/ambari-logsearch-logfeeder-2.7.8.4.0.jar started by root in /var/lib/ambari-agent)
2024-09-12 17:17:52,896 [main] INFO  org.springframework.boot.SpringApplication (SpringApplication.java:632) - No active profile set, falling back to 1 default profile: "default"
2024-09-12 17:17:53,546 [main] WARN  org.springframework.context.support.AbstractApplicationContext (AbstractApplicationContext.java:599) - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationConfig': Unsatisfied dependency expressed through field 'logFeederProps'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'logFeederProps': Unsatisfied dependency expressed through field 'logFeederSecurityConfig'; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'applicationConfig': Requested bean is currently in creation: Is there an unresolvable circular reference?
2024-09-12 17:17:53,555 [main] INFO  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener (ConditionEvaluationReportLoggingListener.java:136) -

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-09-12 17:17:53,585 [main] ERROR org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter (LoggingFailureAnalysisReporter.java:40) -

***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

???????
|  applicationConfig (field private org.apache.ambari.logfeeder.conf.LogFeederProps org.apache.ambari.logfeeder.conf.ApplicationConfig.logFeederProps)
?     ?
|  logFeederProps (field private org.apache.ambari.logfeeder.conf.LogFeederSecurityConfig org.apache.ambari.logfeeder.conf.LogFeederProps.logFeederSecurityConfig)
???????


Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.
```

**Comment by Nazarii-Melnyk** [comment]
> Logfeeder can't start. Logs:
> 
> ```
> 024-09-12 17:17:52,884 [main] INFO  org.springframework.boot.StartupInfoLogger (StartupInfoLogger.java:55) - Starting LogFeeder using Java 1.8.0_422 on isv-s-hdp-mng-01.example.com with PID 2724410 (/usr/lib/ambari-logsearch-logfeeder/libs/ambari-logsearch-logfeeder-2.7.8.4.0.jar started by root in /var/lib/ambari-agent)
> 2024-09-12 17:17:52,896 [main] INFO  org.springframework.boot.SpringApplication (SpringApplication.java:632) - No active profile set, falling back to 1 default profile: "default"
> 2024-09-12 17:17:53,546 [main] WARN  org.springframework.context.support.AbstractApplicationContext (AbstractApplicationContext.java:599) - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationConfig': Unsatisfied dependency expressed through field 'logFeederProps'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'logFeederProps': Unsatisfied dependency expressed through field 'logFeederSecurityConfig'; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'applicationConfig': Requested bean is currently in creation: Is there an unresolvable circular reference?
> 2024-09-12 17:17:53,555 [main] INFO  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener (ConditionEvaluationReportLoggingListener.java:136) -
> 
> Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
> 2024-09-12 17:17:53,585 [main] ERROR org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter (LoggingFailureAnalysisReporter.java:40) -
> 
> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> The dependencies of some of the beans in the application context form a cycle:
> 
> ???????
> |  applicationConfig (field private org.apache.ambari.logfeeder.conf.LogFeederProps org.apache.ambari.logfeeder.conf.ApplicationConfig.logFeederProps)
> ?     ?
> |  logFeederProps (field private org.apache.ambari.logfeeder.conf.LogFeederSecurityConfig org.apache.ambari.logfeeder.conf.LogFeederProps.logFeederSecurityConfig)
> ???????
> 
> 
> Action:
> 
> Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.
> ```

This error occurred due to an upgrade 
versions of `spring.boot dependencies` to version 2.7.18. Reverting to the default version (2.1.5.RELEASE) solved this problem.
